In [1]:
import pandas as pd
import numpy as np

In [2]:
x=pd.read_json("./51628766/message.json")
x.columns
q=x['text'] 
q

0          3603 Sentinel has a large package at the garage
1                          3101 sentinel package by garage
2        3111 sentinel you have a package at your front...
3                 6210 Monitor has a package at the garage
4        someone did tell us this, we live next door to...
                               ...
23070                                         Good stuff!
23071       Steven Marcus added Jerome Brown to the group.
23072             Steven Marcus changed the group's avatar
23073             Steven Marcus changed the group's avatar
23074         Steven Marcus added Charika T. to the group.
Name: text, Length: 23075, dtype: object

In [50]:
x['created_at']
x['text'].str.len().max()

np.float64(1000.0)

In [19]:

print(f'{x.iloc[716]}')

attachments       [{'type': 'reply', 'user_id': '13880987', 'rep...
avatar_url                                                     None
created_at                                      2025-04-24 19:55:56
favorited_by                                                     []
group_id                                                   51628766
id                                               174552455653317664
name                                                     Jose Vides
sender_id                                                  90211445
sender_type                                                    user
source_guid            android-64257f76-45b9-46a2-8975-2fede0203ba5
system                                                        False
text              She's currently 4 yrs old. Instructions will b...
user_id                                                    90211445
platform                                                         gm
pinned_at                                                       NaT
pinned_by
event                                                           NaN
updated_at                                                      NaT
reactions                                                       NaN
deleted_at                                                      NaT
deletion_actor                                                  NaN
Name: 716, dtype: object

In [20]:

c=x['updated_at'] == None
c

0        False
1        False
2        False
3        False
4        False
         ...
23070    False
23071    False
23072    False
23073    False
23074    False
Name: updated_at, Length: 23075, dtype: bool

In [28]:
r=x[x['name']=="Jim Hagelin"]
r

,attachments,avatar_url,created_at,favorited_by,group_id,id,name,sender_id,sender_type,source_guid,...,text,user_id,platform,pinned_at,pinned_by,event,updated_at,reactions,deleted_at,deletion_actor
113,[],https://i.groupme.com/1272x1696.jpeg.ceec9f207...,2025-07-02 11:41:32,[],51628766,175145649210788288,Jim Hagelin,102385541,user,android-e79b1552-6858-48fc-8cc5-468db74ac457,...,Does anyone happen to know what the deal is wi...,102385541,gm,NaT,,NaN,NaT,NaN,NaT,NaN
118,"[{'type': 'reply', 'user_id': '90207816', 'rep...",https://i.groupme.com/1272x1696.jpeg.ceec9f207...,2025-06-30 19:50:44,[],51628766,175131304446431744,Jim Hagelin,102385541,user,android-b842cbc7-0d55-4e54-87e7-1f518d287660,...,It's very weird that the garage has a GFCI out...,102385541,gm,NaT,,NaN,NaT,NaN,NaT,NaN
125,[],https://i.groupme.com/1272x1696.jpeg.ceec9f207...,2025-06-27 19:55:40,"[103876934, 13880987, 39240515]",51628766,175105414004296096,Jim Hagelin,102385541,user,android-98802fa9-7077-4843-891e-72f61ee68c01,...,That's what happens when I wake up early to ma...,102385541,gm,NaT,,NaN,NaT,"[{'type': 'unicode', 'user_ids': ['103876934',...",NaT,NaN
129,[],https://i.groupme.com/1272x1696.jpeg.ceec9f207...,2025-06-27 14:07:56,[],51628766,175103327667700480,Jim Hagelin,102385541,user,android-206e093e-3302-417e-9678-62221a8ccd9f,...,"There's some stuff under there, I don't rememb...",102385541,gm,NaT,,NaN,NaT,NaN,NaT,NaN
130,[],https://i.groupme.com/1272x1696.jpeg.ceec9f207...,2025-06-27 14:07:40,[],51628766,175103326002385920,Jim Hagelin,102385541,user,android-3583deb2-d15f-488c-b81c-dca3975516d8,...,Lift the white button cover on the thing on th...,102385541,gm,NaT,,NaN,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9582,[],None,2022-11-03 15:11:47,[73786170],51628766,166748830703087680,Jim Hagelin,102385541,user,android-2fac8bbb-99b8-4645-a068-8922c949da0d,...,WMATA used to run an express bus from Greenbel...,102385541,gm,NaT,,NaN,NaT,"[{'type': 'emoji', 'pack_id': '1', 'pack_index...",NaT,NaN
9587,"[{'type': 'image', 'url': 'https://i.groupme.c...",None,2022-11-03 13:45:23,[86543058],51628766,166748312391678272,Jim Hagelin,102385541,user,android-34991170-6392-42af-904d-f099875c24df,...,All the signage was changed in September. The...,102385541,gm,NaT,,NaN,NaT,"[{'type': 'emoji', 'pack_id': '1', 'pack_index...",NaT,NaN
9652,"[{'type': 'image', 'url': 'https://i.groupme.c...",None,2022-10-31 20:35:14,"[13785622, 27464130, 33892669, 3598471, 366277...",51628766,166724851407221120,Jim Hagelin,102385541,user,android-c42e3505-4660-4902-bd5d-160e52ff03ac,...,Candy at 6203 Herald. I'm too lazy to go up a...,102385541,gm,NaT,,NaN,NaT,"[{'type': 'emoji', 'pack_id': '1', 'pack_index...",NaT,NaN
10243,"[{'type': 'reply', 'user_id': '27853116', 'rep...",None,2022-09-08 23:39:35,[],51628766,166268037525461856,Jim Hagelin,102385541,user,android-57b0af05-9295-4395-9cd7-387228d11509,...,"I use mint mobile, service in this area is fin...",102385541,gm,NaT,,NaN,NaT,NaN,NaT,NaN
10258,[],None,2022-09-08 18:16:29,"[13785622, 73786170, 90207816]",51628766,166266098993954144,Jim Hagelin,102385541,user,android-c8ab3f30-9ab4-4d5a-9d9d-c4012a6063a0,...,If you look closely at the signage at the Metr...,102385541,gm,NaT,,NaN,NaT,"[{'type': 'emoji', 'pack_id': '1', 'pack_index...",NaT,NaN

In [48]:
x['attachments'].str.capitalize()

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
23070   NaN
23071   NaN
23072   NaN
23073   NaN
23074   NaN
Name: attachments, Length: 23075, dtype: float64

In [30]:

l=r[r['attachments'].apply(len).astype(bool)]
l['attachments']

118      [{'type': 'reply', 'user_id': '90207816', 'rep...
417      [{'type': 'reply', 'user_id': '93354386', 'rep...
448      [{'loci': [[0, 10]], 'type': 'mentions', 'user...
753      [{'loci': [[23, 11]], 'type': 'mentions', 'use...
1188     [{'type': 'reply', 'user_id': '93875255', 'rep...
1501     [{'type': 'reply', 'user_id': '103876934', 're...
1513     [{'type': 'reply', 'user_id': '118453924', 're...
1835     [{'source_url': 'https://i.groupme.com/1500x20...
2174     [{'type': 'image', 'url': 'https://i.groupme.c...
2488     [{'type': 'image', 'url': 'https://i.groupme.c...
2589     [{'type': 'reply', 'user_id': '33892669', 'rep...
2891     [{'type': 'reply', 'user_id': '6377932', 'repl...
3308     [{'type': 'image', 'url': 'https://i.groupme.c...
3309     [{'type': 'image', 'url': 'https://i.groupme.c...
3338     [{'source_url': 'https://i.groupme.com/793x141...
3400     [{'type': 'reply', 'user_id': '46885499', 'rep...
3872     [{'type': 'reply', 'user_id': '90207816', 'rep...
4002     [{'type': 'reply', 'user_id': '2289793', 'repl...
4133     [{'type': 'reply', 'user_id': '82793262', 'rep...
4418     [{'source_url': 'https://i.groupme.com/528x104...
4449     [{'type': 'reply', 'user_id': '3662770', 'repl...
4452     [{'type': 'reply', 'user_id': '39051623', 'rep...
4455     [{'type': 'image', 'url': 'https://i.groupme.c...
4457     [{'type': 'image', 'url': 'https://i.groupme.c...
5481     [{'type': 'reply', 'user_id': '106903408', 're...
6144     [{'type': 'image', 'url': 'https://i.groupme.c...
7855     [{'type': 'reply', 'user_id': '72890589', 'rep...
8549     [{'loci': [[53, 6]], 'type': 'mentions', 'user...
9587     [{'type': 'image', 'url': 'https://i.groupme.c...
9652     [{'type': 'image', 'url': 'https://i.groupme.c...
10243    [{'type': 'reply', 'user_id': '27853116', 'rep...
Name: attachments, dtype: object

In [10]:
pd.concat([x['text'],x['name']],axis=1)

                                                    text           name
0        3603 Sentinel has a large package at the garage            Jim
1                        3101 sentinel package by garage        Jarad B
2      3111 sentinel you have a package at your front...  Kyng Clemonts
3               6210 Monitor has a package at the garage            Jim
4      someone did tell us this, we live next door to...  Crystal Araka
...                                                  ...            ...
23070                                       Good stuff!    Jerome Brown
23071     Steven Marcus added Jerome Brown to the group.        GroupMe
23072           Steven Marcus changed the group's avatar        GroupMe
23073           Steven Marcus changed the group's avatar        GroupMe
23074       Steven Marcus added Charika T. to the group.        GroupMe

[23075 rows x 2 columns]